### PR TITLE
Added missing entry to modman file

### PR DESCRIPTION
**Pull request by sreichel**
- see https://github.com/OpenMage/magento-lts/issues/4093

### CODE REVIEW

**Review by addison74 — APPROVED** [review]

**Review by addison74 — APPROVED** [review]

**Comment by sreichel** [comment]
@colinmollenhour another easy one?

**Comment by sreichel** [comment]
@colinmollenhour thanks. New release please :)

**Comment by colinmollenhour** [comment]
> @colinmollenhour thanks. New release please :)

I published this right after merging: https://github.com/OpenMage/module-mage-pagecache/releases/tag/v1.0.1

**Comment by sreichel** [comment]
Thanks, Have not seen it.

**Pull request merged**
